[package]
name = "validator"
version = "0.1.0"
edition = "2021"
description = "Cobotium validator utilities"

[dependencies]
solana-validator = "1.17.11"
clap = { version = "3.2", features = ["derive"] }

[[bin]]
name = "cobotium-validator"
path = "src/main.rs"
