[package]
name = "cobotium-cli"
version = "0.1.0"
edition = "2021"
description = "Cobotium CLI: Manage your Solana wallet and CBT token"
license = "MIT"
authors = ["arod"]
repository = "https://github.com/YOUR_GITHUB_USERNAME/cobotium"
readme = "README.md"

[[bin]]
name = "cobotium-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
solana-client = "1.17.11"
solana-sdk = "1.17.11"
spl-token = "3.5.0"
spl-associated-token-account = "1.1.1"
shellexpand = "2.1"