[package]
name = "cobotium-sdk"
version = "0.1.0"
edition = "2021"
description = "Cobotium SDK for interacting with the Cobotium Token Program"

[dependencies]
solana-sdk = "1.17.11"
solana-client = "1.17.11"
solana-program = "1.17.11"
borsh = "0.10.3"
borsh-derive = "0.10.3"
thiserror = "1.0"
cobotium-program = { path = "../cobotium-program", features = ["no-entrypoint"] }