[package]
name = "cobotium-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
solana-client = "1.17.11"
solana-program = "1.17.11"
solana-sdk = "1.17.11"
shellexpand = "2"